/**
 * One-off: complete SSL 160's employee record and issue her appointment letter
 * in the current format.
 *
 * DRY RUN unless --apply is passed.
 *
 * Every value written here is RECOVERED, not invented:
 *   · CTC 228,000      — from her own offer AND the appointment letter the
 *                        portal generated and emailed her on 8 Sep 2026.
 *   · 60/30/10 split   — the split that letter already stated
 *                        (136,800 / 68,400 / 22,800 on 228,000). The new letter
 *                        therefore quotes exactly the same money.
 *   · designation      — "Billing Execuctive" is a misspelling of Executive,
 *                        carried from the candidate record into the employee one
 *                        and onto the issued letter.
 *
 * Her 8 Sep letter is BACKED UP to disk before being superseded, because it was
 * emailed to her and filing two appointment letters against one employee leaves
 * nobody able to say which is in force.
 */
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const connectDB = require('../config/db');
const mongoose = require('mongoose');

const EmployeeProfile = require('../models/EmployeeProfile');
const SalaryStructure = require('../models/SalaryStructure');
const User = require('../models/User');
const Document = require('../models/Document');
const { PII_CATEGORIES } = require('../models/Document');
const storage = require('../services/storage');
const { letterData } = require('../controllers/employeeLetterController');
const { renderAppointmentLetter, resolveLetterBody } = require('../services/letterPdf');
const { getBranding } = require('../services/branding');
require('../models/Company');

const APPLY = process.argv.includes('--apply');
const CODE = 'SSL 160';
const CTC = 228000;
const STRUCTURE_NAME = 'Standard 60/30/10';
const BACKUP_DIR = process.env.BACKUP_DIR || path.join(__dirname, '..', '..', 'letter-backups');

const loose = (s) => String(s || '').replace(/[\s\-_]/g, '').toUpperCase();
const say = (...a) => console.log(...a);
const act = (what) => say(`  ${APPLY ? '[done]' : '[would]'} ${what}`);

(async () => {
  await connectDB();
  say(`\n${APPLY ? 'APPLYING' : 'DRY RUN'} — ${CODE}\n`);

  const all = await EmployeeProfile.find({}, 'employeeCode').lean();
  const hit = all.find((p) => loose(p.employeeCode) === loose(CODE));
  if (!hit) throw new Error(`No employee with code "${CODE}".`);
  const profile = await EmployeeProfile.findById(hit._id).populate('user', 'firstName lastName fullName email');

  say(`Employee: ${[profile.user.firstName, profile.user.lastName].filter(Boolean).join(' ')} <${profile.user.email}>`);

  // ---------------------------------------------------------- 1. structure ---
  let structure = await SalaryStructure.findOne({ name: STRUCTURE_NAME });
  if (!structure) {
    act(`create salary structure "${STRUCTURE_NAME}" (basic 60 / hra 30 / special 10)`);
    if (APPLY) {
      structure = await SalaryStructure.create({
        name: STRUCTURE_NAME,
        description: 'Basic 60%, HRA 30%, Special Allowance 10% — the split the issued '
          + 'offer and appointment letters already state.',
        isActive: true,
        components: {
          basicPct: 60, hraPct: 30, specialAllowancePct: 10, conveyancePct: 0, medicalPct: 0, ltaPct: 0,
        },
      });
    }
  } else {
    say(`  [skip] salary structure "${STRUCTURE_NAME}" already exists`);
  }

  // ------------------------------------------------------------ 2. profile ---
  const changes = [];
  if (!Number(profile.annualCtc)) changes.push(['annualCtc', profile.annualCtc, CTC]);
  if (!profile.salaryStructure) changes.push(['salaryStructure', null, STRUCTURE_NAME]);
  if (profile.designation === 'Billing Execuctive') changes.push(['designation', profile.designation, 'Billing Executive']);

  if (!changes.length) say('  [skip] record already complete');
  changes.forEach(([f, from, to]) => act(`set ${f}: ${JSON.stringify(from)} -> ${JSON.stringify(to)}`));

  if (APPLY && changes.length) {
    if (!Number(profile.annualCtc)) profile.annualCtc = CTC;
    if (!profile.salaryStructure) profile.salaryStructure = structure._id;
    if (profile.designation === 'Billing Execuctive') profile.designation = 'Billing Executive';
    await profile.save();
  }

  // ------------------------------------------- 3. back up the old letter -----
  const previous = await Document.find({
    employee: profile._id,
    category: 'AppointmentLetter',
    $or: [
      { generatedBy: { $in: ['employee-letter', 'candidate-letter'] } },
      { note: /^Generated by the portal/ },
    ],
  });
  for (const old of previous) {
    const dest = path.join(BACKUP_DIR, `${profile.employeeCode.replace(/\s/g, '')}-${old.fileName}`);
    act(`back up "${old.fileName}" (${old.status}) -> ${dest}`);
    if (APPLY) {
      fs.mkdirSync(BACKUP_DIR, { recursive: true });
      // eslint-disable-next-line no-await-in-loop
      fs.writeFileSync(dest, await storage.readBuffer(old.storagePath));
    }
  }

  // ------------------------------------------------------- 4. the letter -----
  const fresh = await EmployeeProfile.findById(profile._id)
    .populate('user', 'firstName lastName fullName email')
    .populate('reportingManager', 'firstName lastName fullName');
  const st = APPLY ? await SalaryStructure.findById(fresh.salaryStructure).lean() : (structure ? structure.toObject() : {
    name: STRUCTURE_NAME,
    components: { basicPct: 60, hraPct: 30, specialAllowancePct: 10, conveyancePct: 0, medicalPct: 0, ltaPct: 0 },
  });

  const data = letterData(
    APPLY ? fresh : Object.assign(fresh, { annualCtc: CTC, designation: 'Billing Executive' }),
    st,
    { workingHours: '10:00 AM to 7:00 PM', probationMonths: 3, noticePeriodDays: 30 },
  );
  data.body = await resolveLetterBody('appointment', data);
  data.brand = await getBranding();

  say('\nThe letter will state:');
  say(`  name        ${data.candidateName}`);
  say(`  designation ${data.designation}`);
  say(`  CTC         ${data.ctcAnnual}`);
  say(`  basic/hra/special  ${data.basic} / ${data.hra} / ${data.specialAllowance}`);

  const buffer = await renderAppointmentLetter(data);
  const fileName = `Appointment-Letter-${String(data.candidateName).replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '')}.pdf`;
  const preview = path.join(BACKUP_DIR, `PREVIEW-${fileName}`);
  fs.mkdirSync(BACKUP_DIR, { recursive: true });
  fs.writeFileSync(preview, buffer);
  say(`\n  rendered (${(buffer.length / 1024).toFixed(0)} KB) -> ${preview}`);

  // --------------------------------------------------------- 5. file it -----
  const actor = await User.findOne({ role: 'SuperAdmin' }).select('_id fullName').lean();
  act(`file "${fileName}" against the employee, replacing ${previous.length} previous portal letter(s)`);
  if (APPLY) {
    const saved = await storage.saveBuffer({
      buffer, ownerType: 'employee', ownerId: profile._id, originalName: fileName,
    });
    for (const old of previous) {
      try { await storage.remove(old.storagePath); } catch (e) { console.error('  old bytes:', e.message); }
      await old.deleteOne();
    }
    await Document.create({
      employee: profile._id,
      category: 'AppointmentLetter',
      fileName,
      storagePath: saved.storagePath,
      mime: 'application/pdf',
      sizeBytes: saved.sizeBytes,
      sha256: saved.sha256,
      isPii: PII_CATEGORIES.includes('AppointmentLetter'),
      uploadedBy: actor?._id,
      note: 'Re-issued from the employee record in the current letter format '
        + '(supersedes the letter of 08 Sept 2026; same figures)',
      status: 'Submitted',
      generatedBy: 'employee-letter',
    });
  }

  say(APPLY ? '\nDone.' : '\nDry run only — re-run with --apply to make these changes.');
  await mongoose.connection.close();
})().catch(async (e) => {
  console.error('FAILED:', e.message);
  try { await mongoose.connection.close(); } catch { /* already closed */ }
  process.exit(1);
});
